# Generated by Django 6.0.4 on 2026-04-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.call'),
        ),
    ]
