import asyncio
import logging
from livekit import agents, rtc
from asgiref.sync import sync_to_async
from apps.ai_engine.models import AIConfig
from apps.ai_engine.executor import GraphExecutor

logger = logging.getLogger(__name__)

class TelephonyBridge:
    """
    Acts as the middleware between the LiveKit RTC connection and the Django GraphExecutor.
    It reads raw PCM audio from the user and pipes it into the Engine, and takes TTS
    audio from the Engine and pushes it back into the LiveKit Room.
    """
    
    def __init__(self, ctx: agents.JobContext, tenant_id: int):
        self.ctx = ctx
        self.tenant_id = tenant_id
        self.executor = None
        self.engine_tasks = []
        self.source = rtc.AudioSource(sample_rate=16000, num_channels=1)

    @sync_to_async
    def get_tenant_graph(self):
        # Retrieve the graph config for the specific tenant
        # In a real scenario, this would filter by active campaign or tenant
        config = AIConfig.objects.filter(tenant_id=self.tenant_id).first()
        if config:
            return config.graph_json
        
        # Fallback dummy graph
        return {
            "nodes": [
                {"id": "stt_1", "type": "STT", "config": {"provider": "deepgram"}},
                {"id": "llm_1", "type": "LLM", "config": {"provider": "gemini"}},
                {"id": "tts_1", "type": "TTS", "config": {"provider": "cartesia"}}
            ],
            "edges": [
                {"from": "stt_1", "to": "llm_1"},
                {"from": "llm_1", "to": "tts_1"}
            ]
        }

    async def start(self):
        graph_json = await self.get_tenant_graph()
        call_id = self.ctx.room.name
        
        logger.info(f"Starting Telephony Bridge for Call: {call_id}")
        
        # 1. Initialize and start the Graph Executor
        self.executor = GraphExecutor(graph_json=graph_json, call_id=call_id)
        self.engine_tasks = await self.executor.start()
        
        # 2. Publish the Agent's Audio Track to the room
        track = rtc.LocalAudioTrack.create_audio_track("agent_voice", self.source)
        options = rtc.TrackPublishOptions(source=rtc.TrackSource.SOURCE_MICROPHONE)
        await self.ctx.room.local_participant.publish_track(track, options)

        # 3. Listen for User Audio Subscriptions
        self.ctx.room.on("track_subscribed", self.on_track_subscribed)
        
        # 4. Start loop to read TTS audio generated by the engine and push to LiveKit
        asyncio.create_task(self.publish_tts_from_engine())

    def on_track_subscribed(self, track: rtc.Track, publication: rtc.TrackPublication, participant: rtc.RemoteParticipant):
        if track.kind == rtc.TrackKind.KIND_AUDIO:
            logger.info(f"Subscribed to audio track from {participant.identity}")
            asyncio.create_task(self.read_user_audio(track))

    async def read_user_audio(self, track: rtc.Track):
        """Pipes raw audio from LiveKit directly to the Graph Executor STT node."""
        audio_stream = rtc.AudioStream(track)
        async for audio_frame in audio_stream:
            # We push raw audio bytes directly into the Graph
            await self.executor.push_audio(audio_frame.data)

    async def publish_tts_from_engine(self):
        """Pulls generated audio frames from the Graph Executor and plays them in the LiveKit room."""
        # For full implementation, GraphContext would expose an output asyncio.Queue for TTS audio bytes
        while True:
            # Example placeholder logic:
            # tts_audio_frame = await self.executor.context.tts_audio_queue.get()
            # await self.source.capture_frame(tts_audio_frame)
            await asyncio.sleep(0.1)

    async def stop(self):
        await self.executor.stop()
        if self.engine_tasks:
            await asyncio.gather(*self.engine_tasks, return_exceptions=True)
        logger.info("Telephony Bridge stopped cleanly.")

async def worker_entrypoint(ctx: agents.JobContext):
    # This is the entrypoint LiveKit calls when a new room is created
    tenant_id = 1 # In reality, extract this from the room metadata or JWT token
    bridge = TelephonyBridge(ctx, tenant_id=tenant_id)
    await bridge.start()
