# Generated by Django 6.0.4 on 2026-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livekit_room_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RINGING', 'Ringing'), ('IN_PROGRESS', 'In Progress'), ('HUMAN_TAKEOVER', 'Human Takeover'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('duration_sec', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.IntegerField(blank=True, help_text='End-to-end latency if bot', null=True)),
            ],
        ),
    ]
