# Generated by Django 6.0.4 on 2026-04-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='call',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='calls.call'),
        ),
    ]
